# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app_store_gen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppStoreGen(object):
    def setupUi(self, AppStoreGen):
        AppStoreGen.setObjectName("AppStoreGen")
        AppStoreGen.resize(1080, 720)
        AppStoreGen.setMinimumSize(QtCore.QSize(1080, 720))
        AppStoreGen.setMaximumSize(QtCore.QSize(1080, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        AppStoreGen.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        AppStoreGen.setFont(font)
        AppStoreGen.setStyleSheet("QMainWindow {\n"
"    background: transparent; \n"
"}\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AppStoreGen)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(230, 230, 230); ")
        self.centralwidget.setObjectName("centralwidget")
        self.Central_Widget_hor = QtWidgets.QHBoxLayout(self.centralwidget)
        self.Central_Widget_hor.setContentsMargins(0, 0, 0, 0)
        self.Central_Widget_hor.setSpacing(0)
        self.Central_Widget_hor.setObjectName("Central_Widget_hor")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.frame_main.setFont(font)
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(157,128,173);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: ;\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(139, 128, 173), stop: 1 rgb(81, 110, 133));")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(165, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(165, 16777215))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.btn_App_Name_Container_top_padding = QtWidgets.QFrame(self.frame_menus)
        self.btn_App_Name_Container_top_padding.setMinimumSize(QtCore.QSize(0, 15))
        self.btn_App_Name_Container_top_padding.setMaximumSize(QtCore.QSize(16777215, 15))
        self.btn_App_Name_Container_top_padding.setStyleSheet("background: transparent; ")
        self.btn_App_Name_Container_top_padding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_App_Name_Container_top_padding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_App_Name_Container_top_padding.setObjectName("btn_App_Name_Container_top_padding")
        self.layout_menus.addWidget(self.btn_App_Name_Container_top_padding)
        self.btn_App_Name_Container = QtWidgets.QPushButton(self.frame_menus)
        self.btn_App_Name_Container.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_App_Name_Container.sizePolicy().hasHeightForWidth())
        self.btn_App_Name_Container.setSizePolicy(sizePolicy)
        self.btn_App_Name_Container.setMaximumSize(QtCore.QSize(16777215, 55))
        self.btn_App_Name_Container.setStyleSheet("QPushButton {\n"
"    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"\n"
"background: transparent;\n"
"\n"
"\n"
"font: 16pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(90, 175, 255);\n"
"}\n"
"")
        self.btn_App_Name_Container.setFlat(True)
        self.btn_App_Name_Container.setObjectName("btn_App_Name_Container")
        self.layout_menus.addWidget(self.btn_App_Name_Container)
        self.btn_App_Name_Container_title = QtWidgets.QPushButton(self.frame_menus)
        self.btn_App_Name_Container_title.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_App_Name_Container_title.sizePolicy().hasHeightForWidth())
        self.btn_App_Name_Container_title.setSizePolicy(sizePolicy)
        self.btn_App_Name_Container_title.setMaximumSize(QtCore.QSize(16777215, 28))
        self.btn_App_Name_Container_title.setStyleSheet("QPushButton {\n"
"    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"\n"
"background: transparent;\n"
"\n"
"\n"
"font: 16pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 85);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(90, 175, 255);\n"
"}\n"
"")
        self.btn_App_Name_Container_title.setFlat(True)
        self.btn_App_Name_Container_title.setObjectName("btn_App_Name_Container_title")
        self.layout_menus.addWidget(self.btn_App_Name_Container_title)
        self.btn_App_Name_Container_bottom_padding = QtWidgets.QFrame(self.frame_menus)
        self.btn_App_Name_Container_bottom_padding.setMinimumSize(QtCore.QSize(0, 15))
        self.btn_App_Name_Container_bottom_padding.setMaximumSize(QtCore.QSize(16777215, 15))
        self.btn_App_Name_Container_bottom_padding.setStyleSheet("background: transparent; ")
        self.btn_App_Name_Container_bottom_padding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_App_Name_Container_bottom_padding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_App_Name_Container_bottom_padding.setObjectName("btn_App_Name_Container_bottom_padding")
        self.layout_menus.addWidget(self.btn_App_Name_Container_bottom_padding)
        self.btn_toggle_Main = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_Main.sizePolicy().hasHeightForWidth())
        self.btn_toggle_Main.setSizePolicy(sizePolicy)
        self.btn_toggle_Main.setMaximumSize(QtCore.QSize(16777215, 90))
        self.btn_toggle_Main.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background: transparent; \n"
"    border: 0;  \n"
"    font: 14pt \"Noto Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"    /* padding-left: 15px; */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(166, 135, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(118, 99, 136);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(118, 99, 136);\n"
"    /* background-color: rgba(255, 255, 255, 150); */\n"
"    /* color: rgb(118, 99, 136);  */\n"
"    border: none;\n"
"    font-weight: bold; \n"
"}")
        self.btn_toggle_Main.setObjectName("btn_toggle_Main")
        self.layout_menus.addWidget(self.btn_toggle_Main)
        self.btn_toggle_All = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_All.sizePolicy().hasHeightForWidth())
        self.btn_toggle_All.setSizePolicy(sizePolicy)
        self.btn_toggle_All.setMaximumSize(QtCore.QSize(16777215, 90))
        self.btn_toggle_All.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background: transparent; \n"
"    border: 0;  \n"
"    font: 14pt \"Noto Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"    /* padding-left: 15px; */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(166, 135, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(118, 99, 136);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(118, 99, 136);\n"
"    /* background-color: rgba(255, 255, 255, 150); */\n"
"    /* color: rgb(118, 99, 136);  */\n"
"    border: none;\n"
"    font-weight: bold; \n"
"}")
        self.btn_toggle_All.setObjectName("btn_toggle_All")
        self.layout_menus.addWidget(self.btn_toggle_All)
        self.btn_toggle_Update = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_Update.sizePolicy().hasHeightForWidth())
        self.btn_toggle_Update.setSizePolicy(sizePolicy)
        self.btn_toggle_Update.setMaximumSize(QtCore.QSize(16777215, 90))
        self.btn_toggle_Update.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background: transparent; \n"
"    border: 0;  \n"
"    font: 14pt \"Noto Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"    /* padding-left: 15px; */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(166, 135, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(118, 99, 136);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(118, 99, 136);\n"
"    /* background-color: rgba(255, 255, 255, 150); */\n"
"    /* color: rgb(118, 99, 136);  */\n"
"    border: none;\n"
"    font-weight: bold; \n"
"}")
        self.btn_toggle_Update.setObjectName("btn_toggle_Update")
        self.layout_menus.addWidget(self.btn_toggle_Update)
        self.btn_toggle_Uninstall = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_Uninstall.sizePolicy().hasHeightForWidth())
        self.btn_toggle_Uninstall.setSizePolicy(sizePolicy)
        self.btn_toggle_Uninstall.setMaximumSize(QtCore.QSize(16777215, 90))
        self.btn_toggle_Uninstall.setAutoFillBackground(False)
        self.btn_toggle_Uninstall.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background: transparent; \n"
"    border: 0;  \n"
"    font: 14pt \"Noto Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"    /* padding-left: 15px; */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(166, 135, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(118, 99, 136);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(118, 99, 136);\n"
"    /* background-color: rgba(255, 255, 255, 150); */\n"
"    /* color: rgb(118, 99, 136);  */\n"
"    border: none;\n"
"    font-weight: bold; \n"
"}")
        self.btn_toggle_Uninstall.setObjectName("btn_toggle_Uninstall")
        self.layout_menus.addWidget(self.btn_toggle_Uninstall)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_menus.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_menus)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 0, 0, 25)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.verticalLayout_5.addWidget(self.frame_extra_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.frame_content_right.setFont(font)
        self.frame_content_right.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(132, 110, 160), stop:1 rgb(55, 80, 110));")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.frame_content.setFont(font)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.search_bar_top_padding = QtWidgets.QFrame(self.frame_content)
        self.search_bar_top_padding.setMinimumSize(QtCore.QSize(0, 24))
        self.search_bar_top_padding.setMaximumSize(QtCore.QSize(16777215, 26))
        self.search_bar_top_padding.setStyleSheet("background: transparent; ")
        self.search_bar_top_padding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_bar_top_padding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_bar_top_padding.setObjectName("search_bar_top_padding")
        self.verticalLayout_9.addWidget(self.search_bar_top_padding)
        self.content_top_bar_hor_layout = QtWidgets.QHBoxLayout()
        self.content_top_bar_hor_layout.setObjectName("content_top_bar_hor_layout")
        self.content_top_bar_hor_return_btn = QtWidgets.QHBoxLayout()
        self.content_top_bar_hor_return_btn.setObjectName("content_top_bar_hor_return_btn")
        self.search_bar_return_btn = QtWidgets.QPushButton(self.frame_content)
        self.search_bar_return_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.search_bar_return_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.search_bar_return_btn.setStyleSheet("/* border: 3px solid rgba(255, 255, 255, 180); */\n"
"border-radius: 6px;\n"
"font: 12pt \"Noto Mono\";\n"
"font-weight: bold; \n"
"padding-left: 6px;\n"
"padding-top: 2px;\n"
"padding-right: 6px;\n"
"padding-bottom: 2px;")
        self.search_bar_return_btn.setObjectName("search_bar_return_btn")
        self.content_top_bar_hor_return_btn.addWidget(self.search_bar_return_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.content_top_bar_hor_return_btn.addItem(spacerItem1)
        self.content_top_bar_hor_return_btn.setStretch(0, 1)
        self.content_top_bar_hor_return_btn.setStretch(1, 5)
        self.content_top_bar_hor_layout.addLayout(self.content_top_bar_hor_return_btn)
        self.content_top_bar_hor_search = QtWidgets.QHBoxLayout()
        self.content_top_bar_hor_search.setObjectName("content_top_bar_hor_search")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.content_top_bar_hor_search.addItem(spacerItem2)
        self.search_bar_edit = QtWidgets.QLineEdit(self.frame_content)
        self.search_bar_edit.setMinimumSize(QtCore.QSize(395, 0))
        self.search_bar_edit.setMaximumSize(QtCore.QSize(395, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.search_bar_edit.setFont(font)
        self.search_bar_edit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_bar_edit.setAutoFillBackground(False)
        self.search_bar_edit.setStyleSheet("QLineEdit{\n"
"    /* background-color: rgba(255, 255, 255, 200);\n"
"    color: rgba(0, 0, 0, 170);  */\n"
"    border: 3px solid rgba(255, 255, 255, 130);\n"
"    border-radius: 8px;\n"
"    background: transparent;\n"
"    font: 12pt \"Noto Mono\";\n"
"    color: rgba(255, 255, 255, 180); \n"
"    font-weight: bold; \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgba(255, 255, 255, 220);\n"
"    color: rgba(255, 255, 255, 230); \n"
"}")
        self.search_bar_edit.setText("")
        self.search_bar_edit.setMaxLength(50)
        self.search_bar_edit.setObjectName("search_bar_edit")
        self.content_top_bar_hor_search.addWidget(self.search_bar_edit)
        self.search_bar_middle_padding = QtWidgets.QFrame(self.frame_content)
        self.search_bar_middle_padding.setMinimumSize(QtCore.QSize(15, 20))
        self.search_bar_middle_padding.setMaximumSize(QtCore.QSize(15, 20))
        self.search_bar_middle_padding.setStyleSheet("background: transparent; ")
        self.search_bar_middle_padding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_bar_middle_padding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_bar_middle_padding.setObjectName("search_bar_middle_padding")
        self.content_top_bar_hor_search.addWidget(self.search_bar_middle_padding)
        self.search_bar_trigger_btn = QtWidgets.QPushButton(self.frame_content)
        self.search_bar_trigger_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.search_bar_trigger_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.search_bar_trigger_btn.setStyleSheet("/* border: 3px solid rgba(255, 255, 255, 180); */\n"
"border-radius: 6px;\n"
"font: 12pt \"Noto Mono\";\n"
"font-weight: bold; \n"
"padding-left: 6px;\n"
"padding-top: 2px;\n"
"padding-right: 6px;\n"
"padding-bottom: 2px;")
        self.search_bar_trigger_btn.setObjectName("search_bar_trigger_btn")
        self.content_top_bar_hor_search.addWidget(self.search_bar_trigger_btn)
        self.content_top_bar_hor_layout.addLayout(self.content_top_bar_hor_search)
        self.content_top_bar_hor_layout.setStretch(0, 1)
        self.content_top_bar_hor_layout.setStretch(1, 6)
        self.verticalLayout_9.addLayout(self.content_top_bar_hor_layout)
        self.AppStore_stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.AppStore_stackedWidget.setFont(font)
        self.AppStore_stackedWidget.setStyleSheet("background: transparent;")
        self.AppStore_stackedWidget.setObjectName("AppStore_stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_home)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 711, 271))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.page_home_banner_main_hor = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.page_home_banner_main_hor.setContentsMargins(0, 0, 0, 0)
        self.page_home_banner_main_hor.setSpacing(0)
        self.page_home_banner_main_hor.setObjectName("page_home_banner_main_hor")
        self.page_home_banner_main_content = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.page_home_banner_main_content.setMinimumSize(QtCore.QSize(0, 267))
        self.page_home_banner_main_content.setObjectName("page_home_banner_main_content")
        self.page_home_banner_main_hor.addWidget(self.page_home_banner_main_content)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_home)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(719, 19, 181, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.page_home_banner_main_ver = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.page_home_banner_main_ver.setContentsMargins(0, 5, 0, 0)
        self.page_home_banner_main_ver.setSpacing(5)
        self.page_home_banner_main_ver.setObjectName("page_home_banner_main_ver")
        self.page_home_banner_prev_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.page_home_banner_prev_1.setMinimumSize(QtCore.QSize(0, 62))
        self.page_home_banner_prev_1.setObjectName("page_home_banner_prev_1")
        self.page_home_banner_main_ver.addWidget(self.page_home_banner_prev_1)
        self.page_home_banner_prev_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.page_home_banner_prev_2.setMinimumSize(QtCore.QSize(0, 62))
        self.page_home_banner_prev_2.setObjectName("page_home_banner_prev_2")
        self.page_home_banner_main_ver.addWidget(self.page_home_banner_prev_2)
        self.page_home_banner_prev_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.page_home_banner_prev_3.setMinimumSize(QtCore.QSize(0, 62))
        self.page_home_banner_prev_3.setObjectName("page_home_banner_prev_3")
        self.page_home_banner_main_ver.addWidget(self.page_home_banner_prev_3)
        self.page_home_banner_prev_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.page_home_banner_prev_4.setMinimumSize(QtCore.QSize(0, 62))
        self.page_home_banner_prev_4.setObjectName("page_home_banner_prev_4")
        self.page_home_banner_main_ver.addWidget(self.page_home_banner_prev_4)
        self.page_home_tab_view_on_apps = QtWidgets.QTabWidget(self.page_home)
        self.page_home_tab_view_on_apps.setGeometry(QtCore.QRect(6, 299, 701, 331))
        self.page_home_tab_view_on_apps.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    /* border: 2px solid rgba(102, 138, 210, 120); */\n"
"    /* border-radius:8px; */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    /* top: 2px; */\n"
"    /* left:2px; */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 6px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    /* right: 6px; */\n"
"    /* left: 6 px;  */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    /* left: 6px; */\n"
"    /* right: 6 px; */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* border: none; */\n"
"    border: 4px solid rgba(255, 255, 255, 0);\n"
"    background: rgb(255, 255, 255); \n"
"    /* width: 50 px; */\n"
"    height: 16px;\n"
"    font-size : 16px;\n"
"    padding-left: 8 px; \n"
"    padding-right: 8 px;\n"
"        width: 80px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: transparent; \n"
"    /* background: rgba(255, 255, 255, 170); */\n"
"    color: rgb(46, 60, 218);\n"
"    /* color: rgb(81, 85, 133); */\n"
"    font-weight: bold; \n"
"    border-bottom-color: rgb(46, 60, 218);\n"
"    /* margin-bottom: -2px;  */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: transparent;\n"
"    color: rgba(255, 255, 255, 170);\n"
"    padding-bottom: 6px; \n"
"    /* color: rgba(51, 51, 51, 180); */\n"
"    /* color: rgba(128, 128, 128, 180); */\n"
"    /* margin-bottom: -2px; */\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 12px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.page_home_tab_view_on_apps.setObjectName("page_home_tab_view_on_apps")
        self.page_home_web = QtWidgets.QWidget()
        self.page_home_web.setObjectName("page_home_web")
        self.page_home_app_detail = QtWidgets.QPushButton(self.page_home_web)
        self.page_home_app_detail.setGeometry(QtCore.QRect(40, 40, 131, 41))
        self.page_home_app_detail.setObjectName("page_home_app_detail")
        self.page_home_tab_view_on_apps.addTab(self.page_home_web, "")
        self.page_home_movie = QtWidgets.QWidget()
        self.page_home_movie.setObjectName("page_home_movie")
        self.page_home_tab_view_on_apps.addTab(self.page_home_movie, "")
        self.page_home_work = QtWidgets.QWidget()
        self.page_home_work.setObjectName("page_home_work")
        self.page_home_tab_view_on_apps.addTab(self.page_home_work, "")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_home)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(719, 299, 181, 331))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.page_home_chart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.page_home_chart.setContentsMargins(0, 0, 0, 0)
        self.page_home_chart.setSpacing(0)
        self.page_home_chart.setObjectName("page_home_chart")
        self.AppStore_stackedWidget.addWidget(self.page_home)
        self.page_all_apps = QtWidgets.QWidget()
        self.page_all_apps.setObjectName("page_all_apps")
        self.page_all_apps_view_on_apps = QtWidgets.QTabWidget(self.page_all_apps)
        self.page_all_apps_view_on_apps.setGeometry(QtCore.QRect(0, 10, 901, 621))
        self.page_all_apps_view_on_apps.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    /* border: 2px solid rgba(102, 138, 210, 120); */\n"
"    /* border-radius:8px; */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    /* top: 2px; */\n"
"    /* left:2px; */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 6px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    /* right: 6px; */\n"
"    /* left: 6 px;  */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    /* left: 6px; */\n"
"    /* right: 6 px; */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* border: none; */\n"
"    border: 4px solid rgba(255, 255, 255, 0);\n"
"    background: rgb(255, 255, 255); \n"
"    /* width: 50 px; */\n"
"    height: 16px;\n"
"    font-size : 16px;\n"
"    padding-left: 8 px; \n"
"    padding-right: 8 px;\n"
"        width: 60px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: transparent; \n"
"    /* background: rgba(255, 255, 255, 170); */\n"
"    color: rgb(46, 60, 218);\n"
"    /* color: rgb(81, 85, 133); */\n"
"    font-weight: bold; \n"
"    border-bottom-color: rgb(46, 60, 218);\n"
"    /* margin-bottom: -2px;  */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: transparent;\n"
"    color: rgba(255, 255, 255, 170);\n"
"    padding-bottom: 6px; \n"
"    /* color: rgba(51, 51, 51, 180); */\n"
"    /* color: rgba(128, 128, 128, 180); */\n"
"    /* margin-bottom: -2px; */\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 12px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.page_all_apps_view_on_apps.setObjectName("page_all_apps_view_on_apps")
        self.all_apps_all_tab = QtWidgets.QWidget()
        self.all_apps_all_tab.setObjectName("all_apps_all_tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.all_apps_all_tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 901, 551))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.all_apps_vbox_all_tab = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.all_apps_vbox_all_tab.setContentsMargins(0, 0, 0, 0)
        self.all_apps_vbox_all_tab.setSpacing(0)
        self.all_apps_vbox_all_tab.setObjectName("all_apps_vbox_all_tab")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.all_apps_all_tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 540, 901, 41))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.all_apps_vbox_navi_tab = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.all_apps_vbox_navi_tab.setContentsMargins(0, 0, 0, 0)
        self.all_apps_vbox_navi_tab.setObjectName("all_apps_vbox_navi_tab")
        self.page_all_apps_view_on_apps.addTab(self.all_apps_all_tab, "")
        self.all_apps_browser = QtWidgets.QWidget()
        self.all_apps_browser.setObjectName("all_apps_browser")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.all_apps_browser)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 901, 591))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.all_apps_vbox_browser = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.all_apps_vbox_browser.setContentsMargins(0, 0, 0, 0)
        self.all_apps_vbox_browser.setObjectName("all_apps_vbox_browser")
        self.page_all_apps_view_on_apps.addTab(self.all_apps_browser, "")
        self.all_apps_work = QtWidgets.QWidget()
        self.all_apps_work.setObjectName("all_apps_work")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.all_apps_work)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 901, 591))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.all_apps_vbox_work = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.all_apps_vbox_work.setContentsMargins(0, 0, 0, 0)
        self.all_apps_vbox_work.setObjectName("all_apps_vbox_work")
        self.page_all_apps_view_on_apps.addTab(self.all_apps_work, "")
        self.all_apps_entertainment = QtWidgets.QWidget()
        self.all_apps_entertainment.setObjectName("all_apps_entertainment")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.all_apps_entertainment)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 901, 591))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.all_apps_vbox_entertainment = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.all_apps_vbox_entertainment.setContentsMargins(0, 0, 0, 0)
        self.all_apps_vbox_entertainment.setObjectName("all_apps_vbox_entertainment")
        self.page_all_apps_view_on_apps.addTab(self.all_apps_entertainment, "")
        self.AppStore_stackedWidget.addWidget(self.page_all_apps)
        self.page_update = QtWidgets.QWidget()
        self.page_update.setObjectName("page_update")
        self.page_update_view_on_apps = QtWidgets.QTabWidget(self.page_update)
        self.page_update_view_on_apps.setGeometry(QtCore.QRect(0, 10, 901, 621))
        self.page_update_view_on_apps.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    /* border: 2px solid rgba(102, 138, 210, 120); */\n"
"    /* border-radius:8px; */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    /* top: 2px; */\n"
"    /* left:2px; */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 6px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    /* right: 6px; */\n"
"    /* left: 6 px;  */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    /* left: 6px; */\n"
"    /* right: 6 px; */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* border: none; */\n"
"    border: 4px solid rgba(255, 255, 255, 0);\n"
"    background: rgb(255, 255, 255); \n"
"    /* width: 50 px; */\n"
"    height: 16px;\n"
"    font-size : 16px;\n"
"    padding-left: 8 px; \n"
"    padding-right: 8 px;\n"
"        width: 60px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: transparent; \n"
"    /* background: rgba(255, 255, 255, 170); */\n"
"    color: rgb(46, 60, 218);\n"
"    /* color: rgb(81, 85, 133); */\n"
"    font-weight: bold; \n"
"    border-bottom-color: rgb(46, 60, 218);\n"
"    /* margin-bottom: -2px;  */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: transparent;\n"
"    color: rgba(255, 255, 255, 170);\n"
"    padding-bottom: 6px; \n"
"    /* color: rgba(51, 51, 51, 180); */\n"
"    /* color: rgba(128, 128, 128, 180); */\n"
"    /* margin-bottom: -2px; */\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 12px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.page_update_view_on_apps.setObjectName("page_update_view_on_apps")
        self.update_formal_version_app_view = QtWidgets.QWidget()
        self.update_formal_version_app_view.setObjectName("update_formal_version_app_view")
        self.page_update_view_on_apps.addTab(self.update_formal_version_app_view, "")
        self.update_beta_version_app_view = QtWidgets.QWidget()
        self.update_beta_version_app_view.setObjectName("update_beta_version_app_view")
        self.page_update_view_on_apps.addTab(self.update_beta_version_app_view, "")
        self.AppStore_stackedWidget.addWidget(self.page_update)
        self.page_uninstall = QtWidgets.QWidget()
        self.page_uninstall.setObjectName("page_uninstall")
        self.page_uninstall_view_on_apps = QtWidgets.QTabWidget(self.page_uninstall)
        self.page_uninstall_view_on_apps.setGeometry(QtCore.QRect(0, 10, 901, 621))
        self.page_uninstall_view_on_apps.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    /* border: 2px solid rgba(102, 138, 210, 120); */\n"
"    /* border-radius:8px; */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    /* top: 2px; */\n"
"    /* left:2px; */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 6px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    /* right: 6px; */\n"
"    /* left: 6 px;  */\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    /* left: 6px; */\n"
"    /* right: 6 px; */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* border: none; */\n"
"    border: 4px solid rgba(255, 255, 255, 0);\n"
"    background: rgb(255, 255, 255); \n"
"    /* width: 50 px; */\n"
"    height: 16px;\n"
"    font-size : 16px;\n"
"    padding-left: 8 px; \n"
"    padding-right: 8 px;\n"
"        width: 60px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: transparent; \n"
"    /* background: rgba(255, 255, 255, 170); */\n"
"    color: rgb(46, 60, 218);\n"
"    /* color: rgb(81, 85, 133); */\n"
"    font-weight: bold; \n"
"    border-bottom-color: rgb(46, 60, 218);\n"
"    /* margin-bottom: -2px;  */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: transparent;\n"
"    color: rgba(255, 255, 255, 170);\n"
"    padding-bottom: 6px; \n"
"    /* color: rgba(51, 51, 51, 180); */\n"
"    /* color: rgba(128, 128, 128, 180); */\n"
"    /* margin-bottom: -2px; */\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 12px;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.page_uninstall_view_on_apps.setObjectName("page_uninstall_view_on_apps")
        self.uninstall_all_app_view = QtWidgets.QWidget()
        self.uninstall_all_app_view.setObjectName("uninstall_all_app_view")
        self.page_uninstall_view_on_apps.addTab(self.uninstall_all_app_view, "")
        self.uninstall_recommend_app_view = QtWidgets.QWidget()
        self.uninstall_recommend_app_view.setObjectName("uninstall_recommend_app_view")
        self.page_uninstall_view_on_apps.addTab(self.uninstall_recommend_app_view, "")
        self.AppStore_stackedWidget.addWidget(self.page_uninstall)
        self.page_search = QtWidgets.QWidget()
        self.page_search.setObjectName("page_search")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_search)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 891, 621))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.page_search_result_here = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.page_search_result_here.setContentsMargins(0, 0, 0, 0)
        self.page_search_result_here.setSpacing(0)
        self.page_search_result_here.setObjectName("page_search_result_here")
        self.AppStore_stackedWidget.addWidget(self.page_search)
        self.page_app_detail = QtWidgets.QWidget()
        self.page_app_detail.setObjectName("page_app_detail")
        self.app_detail_icon_placeholder = QtWidgets.QPushButton(self.page_app_detail)
        self.app_detail_icon_placeholder.setGeometry(QtCore.QRect(30, 20, 141, 141))
        self.app_detail_icon_placeholder.setObjectName("app_detail_icon_placeholder")
        self.app_detail_name_placeholder = QtWidgets.QLabel(self.page_app_detail)
        self.app_detail_name_placeholder.setGeometry(QtCore.QRect(196, 26, 351, 51))
        self.app_detail_name_placeholder.setStyleSheet("font: 20pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.app_detail_name_placeholder.setObjectName("app_detail_name_placeholder")
        self.app_detail_ver_num_placeholder = QtWidgets.QLabel(self.page_app_detail)
        self.app_detail_ver_num_placeholder.setGeometry(QtCore.QRect(200, 80, 191, 21))
        self.app_detail_ver_num_placeholder.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.app_detail_ver_num_placeholder.setObjectName("app_detail_ver_num_placeholder")
        self.app_detail_size_num_placeholder = QtWidgets.QLabel(self.page_app_detail)
        self.app_detail_size_num_placeholder.setGeometry(QtCore.QRect(420, 80, 191, 21))
        self.app_detail_size_num_placeholder.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.app_detail_size_num_placeholder.setObjectName("app_detail_size_num_placeholder")
        self.app_detail_install_button = QtWidgets.QPushButton(self.page_app_detail)
        self.app_detail_install_button.setGeometry(QtCore.QRect(630, 50, 131, 51))
        self.app_detail_install_button.setStyleSheet("QPushButton {\n"
"  font-size:18pt; color: rgb(255, 255, 255);\n"
"    background-color: rgb(1,77,146);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(1,106,201);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(1,54,102);\n"
"}")
        self.app_detail_install_button.setObjectName("app_detail_install_button")
        self.app_detail_promo_pic_placeholder_1 = QtWidgets.QPushButton(self.page_app_detail)
        self.app_detail_promo_pic_placeholder_1.setGeometry(QtCore.QRect(30, 170, 301, 151))
        self.app_detail_promo_pic_placeholder_1.setObjectName("app_detail_promo_pic_placeholder_1")
        self.app_detail_promo_pic_placeholder_2 = QtWidgets.QPushButton(self.page_app_detail)
        self.app_detail_promo_pic_placeholder_2.setGeometry(QtCore.QRect(350, 170, 301, 151))
        self.app_detail_promo_pic_placeholder_2.setObjectName("app_detail_promo_pic_placeholder_2")
        self.app_detail_software_intro_title = QtWidgets.QLabel(self.page_app_detail)
        self.app_detail_software_intro_title.setGeometry(QtCore.QRect(40, 340, 341, 21))
        self.app_detail_software_intro_title.setStyleSheet("font: 14pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.app_detail_software_intro_title.setObjectName("app_detail_software_intro_title")
        self.app_detail_software_intro_content = QtWidgets.QLabel(self.page_app_detail)
        self.app_detail_software_intro_content.setGeometry(QtCore.QRect(40, 370, 741, 211))
        self.app_detail_software_intro_content.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.app_detail_software_intro_content.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.app_detail_software_intro_content.setWordWrap(True)
        self.app_detail_software_intro_content.setObjectName("app_detail_software_intro_content")
        self.AppStore_stackedWidget.addWidget(self.page_app_detail)
        self.page_cleaner_tools = QtWidgets.QWidget()
        self.page_cleaner_tools.setObjectName("page_cleaner_tools")
        self.cleaner_page_stackedWidget = QtWidgets.QStackedWidget(self.page_cleaner_tools)
        self.cleaner_page_stackedWidget.setGeometry(QtCore.QRect(-1, -1, 861, 681))
        self.cleaner_page_stackedWidget.setObjectName("cleaner_page_stackedWidget")
        self.sub_cleaner_page_main = QtWidgets.QWidget()
        self.sub_cleaner_page_main.setStyleSheet("")
        self.sub_cleaner_page_main.setObjectName("sub_cleaner_page_main")
        self.layoutWidget = QtWidgets.QWidget(self.sub_cleaner_page_main)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 162, 801, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cleaner_page_main_group_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.cleaner_page_main_group_layout.setContentsMargins(0, 0, 0, 0)
        self.cleaner_page_main_group_layout.setObjectName("cleaner_page_main_group_layout")
        self.cleaner_main_icon_placeholder = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_main_icon_placeholder.sizePolicy().hasHeightForWidth())
        self.cleaner_main_icon_placeholder.setSizePolicy(sizePolicy)
        self.cleaner_main_icon_placeholder.setMinimumSize(QtCore.QSize(230, 230))
        self.cleaner_main_icon_placeholder.setText("")
        self.cleaner_main_icon_placeholder.setObjectName("cleaner_main_icon_placeholder")
        self.cleaner_page_main_group_layout.addWidget(self.cleaner_main_icon_placeholder)
        self.cleaner_page_main_btn_ver_group = QtWidgets.QVBoxLayout()
        self.cleaner_page_main_btn_ver_group.setSpacing(0)
        self.cleaner_page_main_btn_ver_group.setObjectName("cleaner_page_main_btn_ver_group")
        self.cleaner_page_main_prompt_hor = QtWidgets.QHBoxLayout()
        self.cleaner_page_main_prompt_hor.setObjectName("cleaner_page_main_prompt_hor")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_main_prompt_hor.addItem(spacerItem3)
        self.cleaner_main_prompt = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_main_prompt.sizePolicy().hasHeightForWidth())
        self.cleaner_main_prompt.setSizePolicy(sizePolicy)
        self.cleaner_main_prompt.setStyleSheet("font: 26pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.cleaner_main_prompt.setObjectName("cleaner_main_prompt")
        self.cleaner_page_main_prompt_hor.addWidget(self.cleaner_main_prompt)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_main_prompt_hor.addItem(spacerItem4)
        self.cleaner_page_main_btn_ver_group.addLayout(self.cleaner_page_main_prompt_hor)
        self.cleaner_page_main_btn_hor = QtWidgets.QHBoxLayout()
        self.cleaner_page_main_btn_hor.setSpacing(0)
        self.cleaner_page_main_btn_hor.setObjectName("cleaner_page_main_btn_hor")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_main_btn_hor.addItem(spacerItem5)
        self.cleaner_main_btn_triggerClean = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_main_btn_triggerClean.sizePolicy().hasHeightForWidth())
        self.cleaner_main_btn_triggerClean.setSizePolicy(sizePolicy)
        self.cleaner_main_btn_triggerClean.setMinimumSize(QtCore.QSize(300, 90))
        self.cleaner_main_btn_triggerClean.setMaximumSize(QtCore.QSize(250, 90))
        self.cleaner_main_btn_triggerClean.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cleaner_main_btn_triggerClean.setFont(font)
        self.cleaner_main_btn_triggerClean.setStyleSheet("QPushButton {\n"
"    background-color: rgb(124,166,82);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171,228,113);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(87,116,57);\n"
"}\n"
"QPushButton {\n"
"    font-size:20pt; color: rgb(255, 255, 255);\n"
"}")
        self.cleaner_main_btn_triggerClean.setObjectName("cleaner_main_btn_triggerClean")
        self.cleaner_page_main_btn_hor.addWidget(self.cleaner_main_btn_triggerClean)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_main_btn_hor.addItem(spacerItem6)
        self.cleaner_page_main_btn_ver_group.addLayout(self.cleaner_page_main_btn_hor)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cleaner_page_main_btn_ver_group.addItem(spacerItem7)
        self.cleaner_page_main_btn_ver_group.setStretch(0, 10)
        self.cleaner_page_main_btn_ver_group.setStretch(1, 11)
        self.cleaner_page_main_btn_ver_group.setStretch(2, 1)
        self.cleaner_page_main_group_layout.addLayout(self.cleaner_page_main_btn_ver_group)
        self.layoutWidget_2 = QtWidgets.QWidget(self.sub_cleaner_page_main)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 570, 467, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.cleaner_page_outd_file_threshold_controller = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.cleaner_page_outd_file_threshold_controller.setContentsMargins(0, 0, 0, 0)
        self.cleaner_page_outd_file_threshold_controller.setSpacing(6)
        self.cleaner_page_outd_file_threshold_controller.setObjectName("cleaner_page_outd_file_threshold_controller")
        self.cleaner_page_outd_file_threshold_prompt_left = QtWidgets.QLabel(self.layoutWidget_2)
        self.cleaner_page_outd_file_threshold_prompt_left.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.cleaner_page_outd_file_threshold_prompt_left.setObjectName("cleaner_page_outd_file_threshold_prompt_left")
        self.cleaner_page_outd_file_threshold_controller.addWidget(self.cleaner_page_outd_file_threshold_prompt_left)
        self.cleaner_page_outd_file_threshold_combo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cleaner_page_outd_file_threshold_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.cleaner_page_outd_file_threshold_combo.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cleaner_page_outd_file_threshold_combo.setStyleSheet("QComboBox {\n"
"    border: 2px solid rgb(185, 179, 255);\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(240, 250, 254);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"        background: white;\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: white;\n"
"        color: rgb(147, 123, 171);\n"
"        font-weight: bold;\n"
"        /* color: rgb(255, 255, 255); */\n"
"}\n"
"\n"
"QComboBox:!enabled {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 16px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: green;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 6px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.cleaner_page_outd_file_threshold_combo.setObjectName("cleaner_page_outd_file_threshold_combo")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_combo.addItem("")
        self.cleaner_page_outd_file_threshold_controller.addWidget(self.cleaner_page_outd_file_threshold_combo)
        self.cleaner_page_outd_file_threshold_prompt_right = QtWidgets.QLabel(self.layoutWidget_2)
        self.cleaner_page_outd_file_threshold_prompt_right.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.cleaner_page_outd_file_threshold_prompt_right.setObjectName("cleaner_page_outd_file_threshold_prompt_right")
        self.cleaner_page_outd_file_threshold_controller.addWidget(self.cleaner_page_outd_file_threshold_prompt_right)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_outd_file_threshold_controller.addItem(spacerItem8)
        self.layoutWidget1 = QtWidgets.QWidget(self.sub_cleaner_page_main)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 520, 461, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.cleaner_page_huge_file_threshold_controller = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.cleaner_page_huge_file_threshold_controller.setContentsMargins(0, 0, 0, 0)
        self.cleaner_page_huge_file_threshold_controller.setSpacing(6)
        self.cleaner_page_huge_file_threshold_controller.setObjectName("cleaner_page_huge_file_threshold_controller")
        self.cleaner_page_huge_file_threshold_prompt_left = QtWidgets.QLabel(self.layoutWidget1)
        self.cleaner_page_huge_file_threshold_prompt_left.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.cleaner_page_huge_file_threshold_prompt_left.setObjectName("cleaner_page_huge_file_threshold_prompt_left")
        self.cleaner_page_huge_file_threshold_controller.addWidget(self.cleaner_page_huge_file_threshold_prompt_left)
        self.cleaner_page_huge_file_threshold_combo = QtWidgets.QComboBox(self.layoutWidget1)
        self.cleaner_page_huge_file_threshold_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.cleaner_page_huge_file_threshold_combo.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cleaner_page_huge_file_threshold_combo.setStyleSheet("QComboBox {\n"
"    border: 2px solid rgb(185, 179, 255);\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(240, 250, 254);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"        background: white;\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: white;\n"
"        color: rgb(147, 123, 171);\n"
"        font-weight: bold;\n"
"        /* color: rgb(255, 255, 255); */\n"
"}\n"
"\n"
"QComboBox:!enabled {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 16px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: green;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 6px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.cleaner_page_huge_file_threshold_combo.setObjectName("cleaner_page_huge_file_threshold_combo")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_combo.addItem("")
        self.cleaner_page_huge_file_threshold_controller.addWidget(self.cleaner_page_huge_file_threshold_combo)
        self.cleaner_page_huge_file_threshold_prompt_right = QtWidgets.QLabel(self.layoutWidget1)
        self.cleaner_page_huge_file_threshold_prompt_right.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgb(255, 255, 255);")
        self.cleaner_page_huge_file_threshold_prompt_right.setObjectName("cleaner_page_huge_file_threshold_prompt_right")
        self.cleaner_page_huge_file_threshold_controller.addWidget(self.cleaner_page_huge_file_threshold_prompt_right)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_page_huge_file_threshold_controller.addItem(spacerItem9)
        self.cleaner_page_main_sep_enabler = QtWidgets.QCheckBox(self.sub_cleaner_page_main)
        self.cleaner_page_main_sep_enabler.setGeometry(QtCore.QRect(590, 432, 231, 21))
        self.cleaner_page_main_sep_enabler.setStyleSheet("QCheckBox {\n"
"    spacing: 6px;\n"
"    font: 12pt \"Noto Mono\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgba(255, 255, 255, 120);\n"
"    background: none;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: none;\n"
"}\n"
"\n"
"QCheckBox::unchecked {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    background: rgb(175,255,94);\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed {\n"
"    background: rgb(80,116,43);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: rgb(132,193,71);\n"
"}")
        self.cleaner_page_main_sep_enabler.setObjectName("cleaner_page_main_sep_enabler")
        self.cleaner_page_stackedWidget.addWidget(self.sub_cleaner_page_main)
        self.sub_cleaner_in_progress = QtWidgets.QWidget()
        self.sub_cleaner_in_progress.setObjectName("sub_cleaner_in_progress")
        self.layoutWidget2 = QtWidgets.QWidget(self.sub_cleaner_in_progress)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 861, 681))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.sub_cleaner_total_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.sub_cleaner_total_layout.setContentsMargins(0, 0, 0, 0)
        self.sub_cleaner_total_layout.setObjectName("sub_cleaner_total_layout")
        self.cleaner_in_progress_top_group_w_pgb = QtWidgets.QVBoxLayout()
        self.cleaner_in_progress_top_group_w_pgb.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.cleaner_in_progress_top_group_w_pgb.setSpacing(0)
        self.cleaner_in_progress_top_group_w_pgb.setObjectName("cleaner_in_progress_top_group_w_pgb")
        self.cleaner_in_progress_top_group = QtWidgets.QHBoxLayout()
        self.cleaner_in_progress_top_group.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.cleaner_in_progress_top_group.setSpacing(0)
        self.cleaner_in_progress_top_group.setObjectName("cleaner_in_progress_top_group")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem10)
        self.cleaner_in_progress_icon_placeholder = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_icon_placeholder.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_icon_placeholder.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_icon_placeholder.setMinimumSize(QtCore.QSize(81, 81))
        self.cleaner_in_progress_icon_placeholder.setMaximumSize(QtCore.QSize(81, 81))
        self.cleaner_in_progress_icon_placeholder.setText("")
        self.cleaner_in_progress_icon_placeholder.setObjectName("cleaner_in_progress_icon_placeholder")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_icon_placeholder)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem11)
        self.cleaner_in_progress_cleanProgress = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_cleanProgress.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_cleanProgress.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_cleanProgress.setMinimumSize(QtCore.QSize(470, 112))
        self.cleaner_in_progress_cleanProgress.setMaximumSize(QtCore.QSize(16777215, 112))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cleaner_in_progress_cleanProgress.setFont(font)
        self.cleaner_in_progress_cleanProgress.setStyleSheet("font: 18pt \"Noto Mono\";\n"
"color: rgb(250, 250, 250);")
        self.cleaner_in_progress_cleanProgress.setObjectName("cleaner_in_progress_cleanProgress")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_cleanProgress)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem13)
        self.cleaner_in_progress_btn_nowClean = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_btn_nowClean.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_btn_nowClean.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_btn_nowClean.setMinimumSize(QtCore.QSize(180, 10))
        self.cleaner_in_progress_btn_nowClean.setMaximumSize(QtCore.QSize(220, 50))
        self.cleaner_in_progress_btn_nowClean.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cleaner_in_progress_btn_nowClean.setFont(font)
        self.cleaner_in_progress_btn_nowClean.setStyleSheet("QPushButton {\n"
"    background-color: rgb(124,166,82);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171,228,113);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(87,116,57);\n"
"}\n"
"QPushButton {\n"
"    font-size:20pt; color: rgb(255, 255, 255);\n"
"}")
        self.cleaner_in_progress_btn_nowClean.setObjectName("cleaner_in_progress_btn_nowClean")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_btn_nowClean)
        self.cleaner_in_progress_top_group_w_pgb.addLayout(self.cleaner_in_progress_top_group)
        self.cleaner_in_progress_pgsBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.cleaner_in_progress_pgsBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.cleaner_in_progress_pgsBar.setStyleSheet("")
        self.cleaner_in_progress_pgsBar.setProperty("value", 24)
        self.cleaner_in_progress_pgsBar.setObjectName("cleaner_in_progress_pgsBar")
        self.cleaner_in_progress_top_group_w_pgb.addWidget(self.cleaner_in_progress_pgsBar)
        self.sub_cleaner_total_layout.addLayout(self.cleaner_in_progress_top_group_w_pgb)
        self.cleaner_in_progress_scroll_basis = QtWidgets.QScrollArea(self.layoutWidget2)
        self.cleaner_in_progress_scroll_basis.setWidgetResizable(True)
        self.cleaner_in_progress_scroll_basis.setObjectName("cleaner_in_progress_scroll_basis")
        self.cleaner_in_progress_filler_widget = QtWidgets.QWidget()
        self.cleaner_in_progress_filler_widget.setGeometry(QtCore.QRect(0, 0, 857, 545))
        self.cleaner_in_progress_filler_widget.setObjectName("cleaner_in_progress_filler_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.cleaner_in_progress_filler_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 861, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cleaner_in_progress_result_display = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cleaner_in_progress_result_display.setContentsMargins(0, 0, 0, 0)
        self.cleaner_in_progress_result_display.setSpacing(0)
        self.cleaner_in_progress_result_display.setObjectName("cleaner_in_progress_result_display")
        self.cleaner_in_progress_scroll_basis.setWidget(self.cleaner_in_progress_filler_widget)
        self.sub_cleaner_total_layout.addWidget(self.cleaner_in_progress_scroll_basis)
        self.cleaner_page_stackedWidget.addWidget(self.sub_cleaner_in_progress)
        self.AppStore_stackedWidget.addWidget(self.page_cleaner_tools)
        self.verticalLayout_9.addWidget(self.AppStore_stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background: transparent; ")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("/* color: rgb(203, 203, 203); */")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("/* color: rgb(203, 203, 203); */")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.Central_Widget_hor.addWidget(self.frame_main)
        AppStoreGen.setCentralWidget(self.centralwidget)

        self.retranslateUi(AppStoreGen)
        self.AppStore_stackedWidget.setCurrentIndex(0)
        self.page_home_tab_view_on_apps.setCurrentIndex(0)
        self.page_all_apps_view_on_apps.setCurrentIndex(0)
        self.page_update_view_on_apps.setCurrentIndex(0)
        self.page_uninstall_view_on_apps.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AppStoreGen)

    def retranslateUi(self, AppStoreGen):
        _translate = QtCore.QCoreApplication.translate
        AppStoreGen.setWindowTitle(_translate("AppStoreGen", "MainWindow"))
        self.btn_App_Name_Container.setText(_translate("AppStoreGen", "蓝狐应用商店"))
        self.btn_App_Name_Container_title.setText(_translate("AppStoreGen", "标题处"))
        self.btn_toggle_Main.setText(_translate("AppStoreGen", "首页"))
        self.btn_toggle_All.setText(_translate("AppStoreGen", "全部"))
        self.btn_toggle_Update.setText(_translate("AppStoreGen", "升级"))
        self.btn_toggle_Uninstall.setText(_translate("AppStoreGen", "卸载"))
        self.search_bar_return_btn.setText(_translate("AppStoreGen", "<返回"))
        self.search_bar_edit.setPlaceholderText(_translate("AppStoreGen", "在此进行搜索..."))
        self.search_bar_trigger_btn.setText(_translate("AppStoreGen", "🔍搜索"))
        self.page_home_banner_main_content.setText(_translate("AppStoreGen", "中心banner"))
        self.page_home_banner_prev_1.setText(_translate("AppStoreGen", "侧边banner_1"))
        self.page_home_banner_prev_2.setText(_translate("AppStoreGen", "侧边banner_2"))
        self.page_home_banner_prev_3.setText(_translate("AppStoreGen", "侧边banner_3"))
        self.page_home_banner_prev_4.setText(_translate("AppStoreGen", "侧边banner_4"))
        self.page_home_app_detail.setText(_translate("AppStoreGen", "App Detail"))
        self.page_home_tab_view_on_apps.setTabText(self.page_home_tab_view_on_apps.indexOf(self.page_home_web), _translate("AppStoreGen", "上网必备"))
        self.page_home_tab_view_on_apps.setTabText(self.page_home_tab_view_on_apps.indexOf(self.page_home_movie), _translate("AppStoreGen", "影音必备"))
        self.page_home_tab_view_on_apps.setTabText(self.page_home_tab_view_on_apps.indexOf(self.page_home_work), _translate("AppStoreGen", "办公必备"))
        self.page_all_apps_view_on_apps.setTabText(self.page_all_apps_view_on_apps.indexOf(self.all_apps_all_tab), _translate("AppStoreGen", "全部"))
        self.page_all_apps_view_on_apps.setTabText(self.page_all_apps_view_on_apps.indexOf(self.all_apps_browser), _translate("AppStoreGen", "浏览器"))
        self.page_all_apps_view_on_apps.setTabText(self.page_all_apps_view_on_apps.indexOf(self.all_apps_work), _translate("AppStoreGen", "办公"))
        self.page_all_apps_view_on_apps.setTabText(self.page_all_apps_view_on_apps.indexOf(self.all_apps_entertainment), _translate("AppStoreGen", "娱乐"))
        self.page_update_view_on_apps.setTabText(self.page_update_view_on_apps.indexOf(self.update_formal_version_app_view), _translate("AppStoreGen", "正式版"))
        self.page_update_view_on_apps.setTabText(self.page_update_view_on_apps.indexOf(self.update_beta_version_app_view), _translate("AppStoreGen", "测试版"))
        self.page_uninstall_view_on_apps.setTabText(self.page_uninstall_view_on_apps.indexOf(self.uninstall_all_app_view), _translate("AppStoreGen", "全部"))
        self.page_uninstall_view_on_apps.setTabText(self.page_uninstall_view_on_apps.indexOf(self.uninstall_recommend_app_view), _translate("AppStoreGen", "  建议卸载  "))
        self.app_detail_icon_placeholder.setText(_translate("AppStoreGen", "图标"))
        self.app_detail_name_placeholder.setText(_translate("AppStoreGen", "软件名称"))
        self.app_detail_ver_num_placeholder.setText(_translate("AppStoreGen", "软件版本"))
        self.app_detail_size_num_placeholder.setText(_translate("AppStoreGen", "软件大小"))
        self.app_detail_install_button.setText(_translate("AppStoreGen", "现在安装"))
        self.app_detail_promo_pic_placeholder_1.setText(_translate("AppStoreGen", "展示图片1"))
        self.app_detail_promo_pic_placeholder_2.setText(_translate("AppStoreGen", "展示图片2"))
        self.app_detail_software_intro_title.setText(_translate("AppStoreGen", "软件简介"))
        self.app_detail_software_intro_content.setText(_translate("AppStoreGen", "这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。这里是软件简介内容的占位符。"))
        self.cleaner_main_prompt.setText(_translate("AppStoreGen", "清理硬盘垃圾，释放电脑性能"))
        self.cleaner_main_btn_triggerClean.setText(_translate("AppStoreGen", "全面清理"))
        self.cleaner_page_outd_file_threshold_prompt_left.setText(_translate("AppStoreGen", "超过"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(0, _translate("AppStoreGen", "三天"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(1, _translate("AppStoreGen", "五天"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(2, _translate("AppStoreGen", "半个月"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(3, _translate("AppStoreGen", "一个月"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(4, _translate("AppStoreGen", "三个月"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(5, _translate("AppStoreGen", "半年"))
        self.cleaner_page_outd_file_threshold_combo.setItemText(6, _translate("AppStoreGen", "一年"))
        self.cleaner_page_outd_file_threshold_prompt_right.setText(_translate("AppStoreGen", "未访问的文件会被标注为长期未访问文件"))
        self.cleaner_page_huge_file_threshold_prompt_left.setText(_translate("AppStoreGen", "超过"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(0, _translate("AppStoreGen", "50MB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(1, _translate("AppStoreGen", "100MB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(2, _translate("AppStoreGen", "200MB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(3, _translate("AppStoreGen", "500MB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(4, _translate("AppStoreGen", "1GB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(5, _translate("AppStoreGen", "2GB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(6, _translate("AppStoreGen", "5GB"))
        self.cleaner_page_huge_file_threshold_combo.setItemText(7, _translate("AppStoreGen", "10GB"))
        self.cleaner_page_huge_file_threshold_prompt_right.setText(_translate("AppStoreGen", "大小的文件会被标注为大型文件"))
        self.cleaner_page_main_sep_enabler.setText(_translate("AppStoreGen", "在独立窗口中启动扫描页面"))
        self.cleaner_in_progress_cleanProgress.setText(_translate("AppStoreGen", "扫描文件中...马上就好，请稍等片刻！"))
        self.cleaner_in_progress_btn_nowClean.setText(_translate("AppStoreGen", "全面清理"))
        self.label_credits.setText(_translate("AppStoreGen", "Alpha version. "))
        self.label_version.setText(_translate("AppStoreGen", "v1.0.0"))
