# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cleaner_sep.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cleaner_Tool_Sep(object):
    def setupUi(self, Cleaner_Tool_Sep):
        Cleaner_Tool_Sep.setObjectName("Cleaner_Tool_Sep")
        Cleaner_Tool_Sep.resize(875, 715)
        Cleaner_Tool_Sep.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Cleaner_Tool_Sep)
        self.centralwidget.setMinimumSize(QtCore.QSize(875, 715))
        self.centralwidget.setMaximumSize(QtCore.QSize(875, 715))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sub_cleaner_total_layout = QtWidgets.QVBoxLayout()
        self.sub_cleaner_total_layout.setObjectName("sub_cleaner_total_layout")
        self.cleaner_in_progress_top_group_w_pgb = QtWidgets.QVBoxLayout()
        self.cleaner_in_progress_top_group_w_pgb.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.cleaner_in_progress_top_group_w_pgb.setSpacing(0)
        self.cleaner_in_progress_top_group_w_pgb.setObjectName("cleaner_in_progress_top_group_w_pgb")
        self.cleaner_in_progress_top_group = QtWidgets.QHBoxLayout()
        self.cleaner_in_progress_top_group.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.cleaner_in_progress_top_group.setSpacing(0)
        self.cleaner_in_progress_top_group.setObjectName("cleaner_in_progress_top_group")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem)
        self.cleaner_in_progress_icon_placeholder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_icon_placeholder.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_icon_placeholder.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_icon_placeholder.setMinimumSize(QtCore.QSize(81, 81))
        self.cleaner_in_progress_icon_placeholder.setMaximumSize(QtCore.QSize(81, 81))
        self.cleaner_in_progress_icon_placeholder.setText("")
        self.cleaner_in_progress_icon_placeholder.setObjectName("cleaner_in_progress_icon_placeholder")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_icon_placeholder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem1)
        self.cleaner_in_progress_cleanProgress = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_cleanProgress.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_cleanProgress.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_cleanProgress.setMinimumSize(QtCore.QSize(470, 112))
        self.cleaner_in_progress_cleanProgress.setMaximumSize(QtCore.QSize(16777215, 112))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cleaner_in_progress_cleanProgress.setFont(font)
        self.cleaner_in_progress_cleanProgress.setStyleSheet("font: 18pt \"Noto Mono\";\n"
"color: rgb(51, 51, 51);")
        self.cleaner_in_progress_cleanProgress.setObjectName("cleaner_in_progress_cleanProgress")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_cleanProgress)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem3)
        self.cleaner_in_progress_btn_nowClean = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleaner_in_progress_btn_nowClean.sizePolicy().hasHeightForWidth())
        self.cleaner_in_progress_btn_nowClean.setSizePolicy(sizePolicy)
        self.cleaner_in_progress_btn_nowClean.setMinimumSize(QtCore.QSize(180, 10))
        self.cleaner_in_progress_btn_nowClean.setMaximumSize(QtCore.QSize(220, 50))
        self.cleaner_in_progress_btn_nowClean.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cleaner_in_progress_btn_nowClean.setFont(font)
        self.cleaner_in_progress_btn_nowClean.setStyleSheet("QPushButton {\n"
"    background-color: rgb(124,166,82);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171,228,113);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(87,116,57);\n"
"}\n"
"QPushButton {\n"
"    font-size:20pt; color: rgb(255, 255, 255);\n"
"}")
        self.cleaner_in_progress_btn_nowClean.setObjectName("cleaner_in_progress_btn_nowClean")
        self.cleaner_in_progress_top_group.addWidget(self.cleaner_in_progress_btn_nowClean)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cleaner_in_progress_top_group.addItem(spacerItem4)
        self.cleaner_in_progress_top_group_w_pgb.addLayout(self.cleaner_in_progress_top_group)
        self.cleaner_in_progress_pgsBar = QtWidgets.QProgressBar(self.centralwidget)
        self.cleaner_in_progress_pgsBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.cleaner_in_progress_pgsBar.setStyleSheet("")
        self.cleaner_in_progress_pgsBar.setProperty("value", 24)
        self.cleaner_in_progress_pgsBar.setObjectName("cleaner_in_progress_pgsBar")
        self.cleaner_in_progress_top_group_w_pgb.addWidget(self.cleaner_in_progress_pgsBar)
        self.sub_cleaner_total_layout.addLayout(self.cleaner_in_progress_top_group_w_pgb)
        self.cleaner_in_progress_scroll_basis = QtWidgets.QScrollArea(self.centralwidget)
        self.cleaner_in_progress_scroll_basis.setWidgetResizable(True)
        self.cleaner_in_progress_scroll_basis.setObjectName("cleaner_in_progress_scroll_basis")
        self.cleaner_in_progress_filler_widget = QtWidgets.QWidget()
        self.cleaner_in_progress_filler_widget.setGeometry(QtCore.QRect(0, 0, 871, 579))
        self.cleaner_in_progress_filler_widget.setObjectName("cleaner_in_progress_filler_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.cleaner_in_progress_filler_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 871, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cleaner_in_progress_result_display = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cleaner_in_progress_result_display.setContentsMargins(0, 0, 0, 0)
        self.cleaner_in_progress_result_display.setSpacing(0)
        self.cleaner_in_progress_result_display.setObjectName("cleaner_in_progress_result_display")
        self.cleaner_in_progress_scroll_basis.setWidget(self.cleaner_in_progress_filler_widget)
        self.sub_cleaner_total_layout.addWidget(self.cleaner_in_progress_scroll_basis)
        self.verticalLayout.addLayout(self.sub_cleaner_total_layout)
        Cleaner_Tool_Sep.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cleaner_Tool_Sep)
        QtCore.QMetaObject.connectSlotsByName(Cleaner_Tool_Sep)

    def retranslateUi(self, Cleaner_Tool_Sep):
        _translate = QtCore.QCoreApplication.translate
        Cleaner_Tool_Sep.setWindowTitle(_translate("Cleaner_Tool_Sep", "MainWindow"))
        self.cleaner_in_progress_cleanProgress.setText(_translate("Cleaner_Tool_Sep", "扫描文件中...马上就好，请稍等片刻！"))
        self.cleaner_in_progress_btn_nowClean.setText(_translate("Cleaner_Tool_Sep", "全面清理"))
