# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_process_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detail_widget(object):
    def setupUi(self, Detail_widget):
        Detail_widget.setObjectName("Detail_widget")
        Detail_widget.resize(300, 500)
        Detail_widget.setMinimumSize(QtCore.QSize(300, 500))
        Detail_widget.setMaximumSize(QtCore.QSize(300, 500))
        Detail_widget.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(132, 110, 160), stop:1 rgb(55, 80, 110));\n"
"\n"
"color: rgb(255, 255, 255); ")
        self.verticalLayoutWidget = QtWidgets.QWidget(Detail_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 281, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Detail_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Detail_Layout.setContentsMargins(0, 0, 0, 0)
        self.Detail_Layout.setObjectName("Detail_Layout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Detail_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(5, 450, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Detail_ButtonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Detail_ButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.Detail_ButtonLayout.setObjectName("Detail_ButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Detail_ButtonLayout.addItem(spacerItem)
        self.button_kill = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_kill.setObjectName("button_kill")
        self.Detail_ButtonLayout.addWidget(self.button_kill)
        spacerItem1 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Detail_ButtonLayout.addItem(spacerItem1)
        self.button_back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_back.setIconSize(QtCore.QSize(16, 16))
        self.button_back.setObjectName("button_back")
        self.Detail_ButtonLayout.addWidget(self.button_back)

        self.retranslateUi(Detail_widget)
        QtCore.QMetaObject.connectSlotsByName(Detail_widget)

    def retranslateUi(self, Detail_widget):
        _translate = QtCore.QCoreApplication.translate
        Detail_widget.setWindowTitle(_translate("Detail_widget", "详细信息"))
        self.button_kill.setText(_translate("Detail_widget", "终止"))
        self.button_back.setText(_translate("Detail_widget", "返回"))
