# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tray_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutPage(object):
    def setupUi(self, AboutPage):
        AboutPage.setObjectName("AboutPage")
        AboutPage.resize(510, 299)
        self.centralwidget = QtWidgets.QWidget(AboutPage)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(132, 110, 160), stop:1 rgb(55, 80, 110));\n"
"\n"
"color: rgb(255, 255, 255); ")
        self.centralwidget.setObjectName("centralwidget")
        self.About_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.About_stackedWidget.setGeometry(QtCore.QRect(0, 0, 511, 301))
        self.About_stackedWidget.setStyleSheet("background: transparent; ")
        self.About_stackedWidget.setObjectName("About_stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.about_header = QtWidgets.QLabel(self.main_page)
        self.about_header.setGeometry(QtCore.QRect(30, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.about_header.setFont(font)
        self.about_header.setStyleSheet("font: 18pt \"Noto Mono\";")
        self.about_header.setObjectName("about_header")
        self.appellation_prompt = QtWidgets.QLabel(self.main_page)
        self.appellation_prompt.setGeometry(QtCore.QRect(30, 90, 451, 91))
        self.appellation_prompt.setMinimumSize(QtCore.QSize(0, 40))
        self.appellation_prompt.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.appellation_prompt.setWordWrap(True)
        self.appellation_prompt.setObjectName("appellation_prompt")
        self.information_prompt = QtWidgets.QLabel(self.main_page)
        self.information_prompt.setGeometry(QtCore.QRect(30, 60, 441, 21))
        self.information_prompt.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.information_prompt.setFont(font)
        self.information_prompt.setStyleSheet("font: 12pt \"Noto Mono\";\n"
"color: rgba(255, 255, 255, 180);")
        self.information_prompt.setWordWrap(True)
        self.information_prompt.setObjectName("information_prompt")
        self.appellation_prompt_2 = QtWidgets.QLabel(self.main_page)
        self.appellation_prompt_2.setGeometry(QtCore.QRect(30, 200, 451, 40))
        self.appellation_prompt_2.setMinimumSize(QtCore.QSize(0, 40))
        self.appellation_prompt_2.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.appellation_prompt_2.setWordWrap(True)
        self.appellation_prompt_2.setObjectName("appellation_prompt_2")
        self.About_stackedWidget.addWidget(self.main_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.About_stackedWidget.addWidget(self.page_2)
        AboutPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutPage)
        QtCore.QMetaObject.connectSlotsByName(AboutPage)

    def retranslateUi(self, AboutPage):
        _translate = QtCore.QCoreApplication.translate
        AboutPage.setWindowTitle(_translate("AboutPage", "MainWindow"))
        self.about_header.setText(_translate("AboutPage", "蓝狐-终端助手"))
        self.appellation_prompt.setText(_translate("AboutPage", "蓝狐是一款面向桌面信创系统的助手类软件，其对应信创芯片提供跨架构适配方案，能为用户与运维人员提供自动化协助。"))
        self.information_prompt.setText(_translate("AboutPage", "CyanFox© 2021"))
        self.appellation_prompt_2.setText(_translate("AboutPage", "海联捷讯科技。版权所有。"))
