# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tray_doublecheck_exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoubleCheckExit(object):
    def setupUi(self, DoubleCheckExit):
        DoubleCheckExit.setObjectName("DoubleCheckExit")
        DoubleCheckExit.resize(510, 299)
        self.centralwidget = QtWidgets.QWidget(DoubleCheckExit)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(250, 116, 77), stop:1 rgb(250, 85, 85));\n"
"\n"
"color: rgb(255, 255, 255); ")
        self.centralwidget.setObjectName("centralwidget")
        self.DCE_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.DCE_stackedWidget.setGeometry(QtCore.QRect(0, 0, 511, 301))
        self.DCE_stackedWidget.setStyleSheet("background: transparent; ")
        self.DCE_stackedWidget.setObjectName("DCE_stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.dce_header = QtWidgets.QLabel(self.main_page)
        self.dce_header.setGeometry(QtCore.QRect(30, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dce_header.setFont(font)
        self.dce_header.setStyleSheet("font: 18pt \"Noto Mono\";")
        self.dce_header.setObjectName("dce_header")
        self.main_prompt = QtWidgets.QLabel(self.main_page)
        self.main_prompt.setGeometry(QtCore.QRect(30, 90, 431, 61))
        self.main_prompt.setMinimumSize(QtCore.QSize(0, 40))
        self.main_prompt.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.main_prompt.setWordWrap(True)
        self.main_prompt.setObjectName("main_prompt")
        self.information_prompt = QtWidgets.QLabel(self.main_page)
        self.information_prompt.setGeometry(QtCore.QRect(30, 160, 441, 50))
        self.information_prompt.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.information_prompt.setFont(font)
        self.information_prompt.setStyleSheet("font: 10pt \"Noto Mono\";\n"
"color: rgba(255, 255, 255, 180);")
        self.information_prompt.setWordWrap(True)
        self.information_prompt.setObjectName("information_prompt")
        self.dce_keep_on_btn = QtWidgets.QPushButton(self.main_page)
        self.dce_keep_on_btn.setGeometry(QtCore.QRect(240, 240, 141, 41))
        self.dce_keep_on_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(124,166,82);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171,228,113);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(87,116,57);\n"
"}\n"
"QPushButton {\n"
"    font-size:16pt; color: rgb(255, 255, 255);\n"
"}")
        self.dce_keep_on_btn.setObjectName("dce_keep_on_btn")
        self.dce_quit_btn = QtWidgets.QPushButton(self.main_page)
        self.dce_quit_btn.setGeometry(QtCore.QRect(400, 245, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.dce_quit_btn.setFont(font)
        self.dce_quit_btn.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size:14pt; color: rgba(255, 255, 255, 200);\n"
"}\n"
"/* QPushButton:hover {\n"
"    background-color: rgb(171,228,113);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(87,116,57);\n"
"} */")
        self.dce_quit_btn.setObjectName("dce_quit_btn")
        self.DCE_stackedWidget.addWidget(self.main_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.DCE_stackedWidget.addWidget(self.page_2)
        DoubleCheckExit.setCentralWidget(self.centralwidget)

        self.retranslateUi(DoubleCheckExit)
        QtCore.QMetaObject.connectSlotsByName(DoubleCheckExit)

    def retranslateUi(self, DoubleCheckExit):
        _translate = QtCore.QCoreApplication.translate
        DoubleCheckExit.setWindowTitle(_translate("DoubleCheckExit", "MainWindow"))
        self.dce_header.setText(_translate("DoubleCheckExit", "确定要退出蓝狐吗？"))
        self.main_prompt.setText(_translate("DoubleCheckExit", "如果您退出蓝狐，这台电脑会失去蓝狐提供的持续保护，存在由不当操作造成系统崩溃的风险。"))
        self.information_prompt.setText(_translate("DoubleCheckExit", "蓝狐能为您的电脑提供各项辅助功能，并能为您的电脑安全保驾护航。\n"
"我们建议您保持蓝狐的持续开启。"))
        self.dce_keep_on_btn.setText(_translate("DoubleCheckExit", "保持开启"))
        self.dce_quit_btn.setText(_translate("DoubleCheckExit", "确认退出"))
