# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tray_report_problem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportProblem(object):
    def setupUi(self, ReportProblem):
        ReportProblem.setObjectName("ReportProblem")
        ReportProblem.resize(778, 550)
        ReportProblem.setMinimumSize(QtCore.QSize(778, 550))
        ReportProblem.setMaximumSize(QtCore.QSize(778, 550))
        self.centralwidget = QtWidgets.QWidget(ReportProblem)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(132, 110, 160), stop:1 rgb(55, 80, 110));\n"
"\n"
"color: rgb(255, 255, 255); ")
        self.centralwidget.setObjectName("centralwidget")
        self.RP_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.RP_stackedWidget.setGeometry(QtCore.QRect(-1, -1, 781, 551))
        self.RP_stackedWidget.setStyleSheet("background: transparent; ")
        self.RP_stackedWidget.setObjectName("RP_stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.report_problem_header = QtWidgets.QLabel(self.main_page)
        self.report_problem_header.setGeometry(QtCore.QRect(30, 20, 661, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.report_problem_header.setFont(font)
        self.report_problem_header.setStyleSheet("font: 18pt \"Noto Mono\";")
        self.report_problem_header.setObjectName("report_problem_header")
        self.appellation_prompt = QtWidgets.QLabel(self.main_page)
        self.appellation_prompt.setGeometry(QtCore.QRect(30, 90, 121, 41))
        self.appellation_prompt.setMinimumSize(QtCore.QSize(0, 40))
        self.appellation_prompt.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.appellation_prompt.setObjectName("appellation_prompt")
        self.appellation_edit = QtWidgets.QLineEdit(self.main_page)
        self.appellation_edit.setGeometry(QtCore.QRect(160, 97, 141, 31))
        self.appellation_edit.setAutoFillBackground(False)
        self.appellation_edit.setStyleSheet("QLineEdit{\n"
"    /* background-color: rgba(255, 255, 255, 200);\n"
"    color: rgba(0, 0, 0, 170);  */\n"
"    border: 3px solid rgba(255, 255, 255, 180);\n"
"    border-radius: 8px;\n"
"    background: transparent;\n"
"    font: 14pt \"Noto Mono\";\n"
"    font-weight: bold; \n"
"}")
        self.appellation_edit.setMaxLength(12)
        self.appellation_edit.setObjectName("appellation_edit")
        self.phone_prompt = QtWidgets.QLabel(self.main_page)
        self.phone_prompt.setGeometry(QtCore.QRect(340, 90, 131, 41))
        self.phone_prompt.setMinimumSize(QtCore.QSize(0, 40))
        self.phone_prompt.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.phone_prompt.setObjectName("phone_prompt")
        self.information_explain_1 = QtWidgets.QLabel(self.main_page)
        self.information_explain_1.setGeometry(QtCore.QRect(30, 135, 689, 20))
        self.information_explain_1.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.information_explain_1.setFont(font)
        self.information_explain_1.setStyleSheet("font: 10pt \"Noto Mono\";\n"
"color: rgba(255, 255, 255, 180);")
        self.information_explain_1.setWordWrap(True)
        self.information_explain_1.setObjectName("information_explain_1")
        self.description_prompt = QtWidgets.QLabel(self.main_page)
        self.description_prompt.setGeometry(QtCore.QRect(30, 190, 241, 40))
        self.description_prompt.setMinimumSize(QtCore.QSize(0, 40))
        self.description_prompt.setStyleSheet("font: 14pt \"Noto Mono\";")
        self.description_prompt.setObjectName("description_prompt")
        self.description_textedit = QtWidgets.QTextEdit(self.main_page)
        self.description_textedit.setGeometry(QtCore.QRect(30, 240, 661, 141))
        self.description_textedit.setStyleSheet("QTextEdit{\n"
"    /* background-color: rgba(255, 255, 255, 200);\n"
"    color: rgba(0, 0, 0, 170);  */\n"
"    border: 3px solid rgba(255, 255, 255, 180);\n"
"    border-radius: 8px;\n"
"    background: transparent;\n"
"    font: 12pt \"Noto Mono\";\n"
"    /* font-weight: bold;  */\n"
"}")
        self.description_textedit.setObjectName("description_textedit")
        self.information_explain_2 = QtWidgets.QLabel(self.main_page)
        self.information_explain_2.setGeometry(QtCore.QRect(30, 390, 689, 20))
        self.information_explain_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.information_explain_2.setFont(font)
        self.information_explain_2.setStyleSheet("font: 10pt \"Noto Mono\";\n"
"color: rgba(255, 255, 255, 180);")
        self.information_explain_2.setWordWrap(True)
        self.information_explain_2.setObjectName("information_explain_2")
        self.rp_submit_btn = QtWidgets.QPushButton(self.main_page)
        self.rp_submit_btn.setGeometry(QtCore.QRect(30, 450, 141, 41))
        self.rp_submit_btn.setStyleSheet("QPushButton {\n"
"    font-size:14pt; color: rgb(255, 255, 255);\n"
"    background-color: rgb(54,183,235);\n"
"}")
        self.rp_submit_btn.setObjectName("rp_submit_btn")
        self.information_explain_3 = QtWidgets.QLabel(self.main_page)
        self.information_explain_3.setGeometry(QtCore.QRect(30, 495, 689, 20))
        self.information_explain_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.information_explain_3.setFont(font)
        self.information_explain_3.setStyleSheet("font: 10pt \"Noto Mono\";\n"
"color: rgba(255, 255, 255, 180);")
        self.information_explain_3.setWordWrap(True)
        self.information_explain_3.setObjectName("information_explain_3")
        self.phone_edit = QtWidgets.QLineEdit(self.main_page)
        self.phone_edit.setGeometry(QtCore.QRect(480, 97, 211, 31))
        self.phone_edit.setAutoFillBackground(False)
        self.phone_edit.setStyleSheet("QLineEdit{\n"
"    /* background-color: rgba(255, 255, 255, 200);\n"
"    color: rgba(0, 0, 0, 170);  */\n"
"    border: 3px solid rgba(255, 255, 255, 180);\n"
"    border-radius: 8px;\n"
"    background: transparent;\n"
"    font: 14pt \"Noto Mono\";\n"
"    font-weight: bold; \n"
"}")
        self.phone_edit.setMaxLength(12)
        self.phone_edit.setObjectName("phone_edit")
        self.RP_stackedWidget.addWidget(self.main_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.RP_stackedWidget.addWidget(self.page_2)
        ReportProblem.setCentralWidget(self.centralwidget)

        self.retranslateUi(ReportProblem)
        QtCore.QMetaObject.connectSlotsByName(ReportProblem)

    def retranslateUi(self, ReportProblem):
        _translate = QtCore.QCoreApplication.translate
        ReportProblem.setWindowTitle(_translate("ReportProblem", "MainWindow"))
        self.report_problem_header.setText(_translate("ReportProblem", "电脑出现了问题？请不要担心：我们乐意为您提供各项服务。"))
        self.appellation_prompt.setText(_translate("ReportProblem", "如何称呼您？"))
        self.phone_prompt.setText(_translate("ReportProblem", "您的联系方式："))
        self.information_explain_1.setText(_translate("ReportProblem", "此处预留的信息仅会提供给维护人员，以方便其与您取得联系。"))
        self.description_prompt.setText(_translate("ReportProblem", "请简要描述您遇到的问题。"))
        self.information_explain_2.setText(_translate("ReportProblem", "您提供的简要描述有助于维护人员预估故障起因，以便其在提供服务时携带必要材料。"))
        self.rp_submit_btn.setText(_translate("ReportProblem", "上报问题"))
        self.information_explain_3.setText(_translate("ReportProblem", "在您上报问题后，我们会生成工单，并尽快为您分配维护人员以处理故障。"))
