# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_util_service_availability.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServiceAvailability(object):
    def setupUi(self, ServiceAvailability):
        ServiceAvailability.setObjectName("ServiceAvailability")
        ServiceAvailability.resize(800, 600)
        ServiceAvailability.setMinimumSize(QtCore.QSize(800, 600))
        ServiceAvailability.setMaximumSize(QtCore.QSize(800, 600))
        ServiceAvailability.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ServiceAvailability)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(y1: 0, y2: 1, stop: 0 rgb(132, 110, 160), stop:1 rgb(55, 80, 110));\n"
"\n"
"color: rgb(255, 255, 255); ")
        self.centralwidget.setObjectName("centralwidget")
        self.service_avil_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.service_avil_stackedWidget.setGeometry(QtCore.QRect(0, 0, 791, 591))
        self.service_avil_stackedWidget.setStyleSheet("background: transparent; ")
        self.service_avil_stackedWidget.setObjectName("service_avil_stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.util_serv_avai_header = QtWidgets.QLabel(self.page_main)
        self.util_serv_avai_header.setGeometry(QtCore.QRect(30, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.util_serv_avai_header.setFont(font)
        self.util_serv_avai_header.setStyleSheet("font: 18pt \"Noto Mono\";")
        self.util_serv_avai_header.setObjectName("util_serv_avai_header")
        self.util_serv_avai_subheader = QtWidgets.QLabel(self.page_main)
        self.util_serv_avai_subheader.setGeometry(QtCore.QRect(30, 80, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.util_serv_avai_subheader.setFont(font)
        self.util_serv_avai_subheader.setStyleSheet("font: 12pt \"Noto Mono\";")
        self.util_serv_avai_subheader.setWordWrap(True)
        self.util_serv_avai_subheader.setObjectName("util_serv_avai_subheader")
        self.util_serv_avai_dev_prog = QtWidgets.QLabel(self.page_main)
        self.util_serv_avai_dev_prog.setGeometry(QtCore.QRect(30, 140, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.util_serv_avai_dev_prog.setFont(font)
        self.util_serv_avai_dev_prog.setStyleSheet("font: 12pt \"Noto Mono\";")
        self.util_serv_avai_dev_prog.setWordWrap(True)
        self.util_serv_avai_dev_prog.setObjectName("util_serv_avai_dev_prog")
        self.service_avil_stackedWidget.addWidget(self.page_main)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.service_avil_stackedWidget.addWidget(self.page_2)
        ServiceAvailability.setCentralWidget(self.centralwidget)

        self.retranslateUi(ServiceAvailability)
        QtCore.QMetaObject.connectSlotsByName(ServiceAvailability)

    def retranslateUi(self, ServiceAvailability):
        _translate = QtCore.QCoreApplication.translate
        ServiceAvailability.setWindowTitle(_translate("ServiceAvailability", "MainWindow"))
        self.util_serv_avai_header.setText(_translate("ServiceAvailability", "服务可用性测试"))
        self.util_serv_avai_subheader.setText(_translate("ServiceAvailability", "通过使用本工具来快速测试内网下各业务的运行状态。"))
        self.util_serv_avai_dev_prog.setText(_translate("ServiceAvailability", "在获取需测试服务的支撑服务器地址后进行本功能的完善。"))
